spring:
  application:
    name: app-web
server:
  port: 8011
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka